/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v11.0
processor: MCIMX6G2xxx05
package_id: MCIMX6G2CVM05
mcu_data: i_mx_2_0
processor_version: 11.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "iomux_config.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: ca7}
- pin_list:
  - {pin_num: A14, peripheral: ECSPI1, signal: ecspi_mosi, pin_signal: LCD_DATA22}
  - {pin_num: C14, peripheral: ECSPI1, signal: ecspi_sclk, pin_signal: LCD_DATA20}
  - {pin_num: B14, peripheral: ECSPI1, signal: 'ecspi_ss, 0', pin_signal: LCD_DATA21}
  - {pin_num: D14, peripheral: GPIO3, signal: 'gpio_io, 24', pin_signal: LCD_DATA19}
  - {pin_num: D1, peripheral: ECSPI1, signal: ecspi_miso, pin_signal: CSI_DATA07}
  - {pin_num: B13, peripheral: GPIO3, signal: 'gpio_io, 22', pin_signal: LCD_DATA17}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-A7[ca7] */
  /* IOMUXC_ECSPI1_MISO_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[32U] = IOMUXC_SELECT_INPUT_DAISY(1U);
  /* IOMUXC_ECSPI1_MOSI_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[33U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_ECSPI1_SCLK_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[31U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_ECSPI1_SS0_B_SELECT_INPUT register modification value */
  IOMUXC_BASE_PTR->SELECT_INPUT[34U] = IOMUXC_SELECT_INPUT_DAISY(0U);
  /* IOMUXC_SW_MUX_CTL_PAD_CSI_DATA07 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[123U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(3U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA17 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[82U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(5U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA19 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[84U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(5U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA20 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[85U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(2U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA21 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[86U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(2U);
  /* IOMUXC_SW_MUX_CTL_PAD_LCD_DATA22 register modification value */
  IOMUXC_BASE_PTR->SW_MUX_CTL_PAD[87U] = IOMUXC_SW_MUX_CTL_PAD_MUX_MODE(2U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
